---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Master template for deployment of the auth gateway service for the CORE"

#Metadata:
#  AWS::CloudFormation::Interface:
#    ParameterGroups:
#    - Label:
#        default: "General information"
#      Parameters:
#      - ProjectName
#      - Environment
#      - Component
#    - Label:
#        default: "VPC setup"
#      Parameters:
#      - VpcCidrBlock
#    ParameterLabels:
#      ProjectName:
#        default: "Project name"
#      VpcCidrBlock:
#        default: "CIDR block for VPC"

Parameters:
  ProjectName:
    Description: "Name of the project"
    Type: "String"
    Default: "hbs"
  Environment:
    Description: "Name of the environment"
    Type: "String"
    Default: "dev"
  Component:
    Description: "Name of the component"
    Type: "String"
    Default: "portal"
  Layer:
    Description: "Name of the layer"
    Type: "String"
    Default: "service-adminportal-base"
  ServiceName:
    Description: "Name of the service"
    Type: "String"
    Default: "adminportal"
  ServiceVersion:
    Description: "Version of the service"
    Type: "String"
    Default: "1.0.0"
#  RepoUser:
#    Description: "nexus user for CodeBuild"
#    Type: "String"
#  RepoPassword:
#    Description: "nexus pw for CodeBuild"
#    Type: "String"
#  VpcCidrBlock:
#    Description: "Please enter the CIDR block for this VPC"
#    Type: "String"
#    Default: "10.186.0.0/19"

Resources:
#  CodeBuildIam:
#    Type: "AWS::CloudFormation::Stack"
#    Properties:
#      TemplateURL: "./codeBuild/iam.yml"
#      Parameters:
#        Environment: !Ref Environment
#        ProjectName: !Ref ProjectName
#
#  CodeBuildProject:
#    Type: "AWS::CloudFormation::Stack"
#    Properties:
#      TemplateURL: "./codeBuild/project.yml"
#      Parameters:
#        ProjectName: !Ref ProjectName
#        Environment: !Ref Environment
#        Component: !Ref Component
#        Layer: !Ref Layer
#        ServiceName: !Ref ServiceName
#        ServiceVersion: !Ref ServiceVersion
##        RepoUser: !Ref RepoUser
##        RepoPassword: !Ref RepoPassword        
#        ServiceRole: !GetAtt CodeBuildIam.Outputs.ServiceRole
##        ServiceRole:
##          Fn::ImportValue: !Sub ${Environment}-${ProjectName}-base-CodeBuildServiceRole

#  CodeBuildProjectDocker:
#    Type: "AWS::CloudFormation::Stack"
#    Properties:
#      TemplateURL: "./codeBuild_docker/project.yml"
#      Parameters:
#        ProjectName: !Ref ProjectName
#        Environment: !Ref Environment
#        Component: !Ref Component
#        Layer: !Ref Layer
#        ServiceName: !Ref ServiceName
#        ServiceVersion: !Ref ServiceVersion
#        RepoUser: !Ref RepoUser
#        RepoPassword: !Ref RepoPassword        
#        ServiceRole: !GetAtt CodeBuildIam.Outputs.ServiceRole
#        ServiceRole:
#          Fn::ImportValue: !Sub ${Environment}-${ProjectName}-base-CodeBuildServiceRole

#  CodeBuildProjectAll:
#    Type: "AWS::CloudFormation::Stack"
#    Properties:
#      TemplateURL: "./codeBuild_all/project.yml"
#      Parameters:
#        ProjectName: !Ref ProjectName
#        Environment: !Ref Environment
#        Component: !Ref Component
#        Layer: !Ref Layer
#        ServiceName: !Ref ServiceName
#        ServiceVersion: !Ref ServiceVersion
#        RepoUser: !Ref RepoUser
#        RepoPassword: !Ref RepoPassword        
#        ServiceRole: !GetAtt CodeBuildIam.Outputs.ServiceRole
#        ServiceRole:
#          Fn::ImportValue: !Sub ${Environment}-${ProjectName}-base-CodeBuildServiceRole

#  ServiceLogGroup:
#    Type: "AWS::CloudFormation::Stack"
#    Properties:
#      TemplateURL: "./ecs/loggroup.yml"
#      Parameters:
#        ProjectName: !Ref ProjectName
#        Environment: !Ref Environment
#        Component: !Ref Component
#        Layer: !Ref Layer
#        ServiceName: !Ref ServiceName
#  ServiceTargetGroup:
#    Type: "AWS::CloudFormation::Stack"
#    Properties:
#      TemplateURL: "./ecs/targetgroup.yml"
#      Parameters:
#        ProjectName: !Ref ProjectName
#        Environment: !Ref Environment
#        Component: !Ref Component
#        Layer: !Ref Layer
#        VpcId:
#          Fn::ImportValue: !Sub "hbs-prod-core-network-VpcId"
#  ServiceListenerRule:
#    Type: "AWS::CloudFormation::Stack"
#    Properties:
#      TemplateURL: "./ecs/listenerrule.yml"
#      Parameters:
#        ListenerArn:
#          Fn::ImportValue: !Sub "hbs-prod-core-base-MicroserviceListenerArn"
#        TargetGroupArn: !GetAtt ServiceTargetGroup.Outputs.TargetGroupArn
  Ecr:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "./ecs/ecr.yml"
      Parameters:
        ProjectName: !Ref ProjectName
        Component: !Ref Component
        Layer: !Ref Layer
        ServiceName: !Ref ServiceName

#  TaskDefinition:
#    Type: "AWS::CloudFormation::Stack"
#    Properties:
#      TemplateURL: "./ecs/taskdefinition.yml"
#      Parameters:
#        ProjectName: !Ref ProjectName
#        Environment: !Ref Environment
#        Component: !Ref Component
#        Layer: !Ref Layer
#        ServiceName: !Ref ServiceName
#        ServiceVersion: !Ref ServiceVersion
#        TaskServiceRoleArn:
#          Fn::ImportValue: !Sub "hbs-prod-core-base-TaskExecutionRoleArn"
#
#  Service:
#    Type: "AWS::CloudFormation::Stack"
#    Properties:
#      TemplateURL: "./ecs/service.yml"
#      Parameters:
#        ProjectName: !Ref ProjectName
#        Environment: !Ref Environment
#        Component: !Ref Component
#        Layer: !Ref Layer
##        ServiceName: !Ref ServiceName
#        ClusterArn:
#          Fn::ImportValue: !Sub "hbs-prod-core-base-MicroserviceClusterArn"
#        TaskDefinitionArn: !GetAtt TaskDefinition.Outputs.TaskDefinitionArn
#        TargetGroupArn: !GetAtt ServiceTargetGroup.Outputs.TargetGroupArn
